version: '2.1'
services:

  nginx:
    image: nginx
    expose:
      - 9999
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx_compose.conf
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  redirector:
    build: .
    expose:
      - 8080
    networks:
      testing_net:
        ipv4_address: 172.28.1.2


#  curl:
#    image: byrnedo/alpine-curl
#    command: http://172.28.1.2:8080/anypath
#    restart: always
#    networks:
#      testing_net:
#        ipv4_address: 172.28.1.3


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16